#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/todolist
#    username: root
#    password: 112233
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#
#jwt:
#  secret:
#    key: 7J206rGwIOuSpOyngOqyjO2emOuTnOuEpOyalC4g7IK066Ck7KO87IS47JqU
##      ================================================== 1

spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret:
    key: 7J206rGwIOuSpOyngOqyjO2emOuTnOuEpOyalC4g7IK066Ck7KO87IS47JqU
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/todolist
    password: 112233

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create